-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- https://wiki.hyprland.org/Configuring/Configuring-Hyprland/


local myColors = require("myColors")

hl.monitor({
    output   = "HDMI-A-1",
    mode     = "3840x2160@120",
    position = "0x0",
    scale    = 1,
    bitdepth = 10,
    cm = "hdr",
})

-- keywords / variables - see https://wiki.hyprland.org/Configuring/Keywords/

local terminal = "kitty"
local fileManager = "thunar"
local menu = "rofi -show combi -modes combi -combi-modes window,drun,run -show-icons -matching fuzzy -theme ~/.config/rofi/tokyonight.rasi"
local wallpaper = "rofi -no-config -theme fullscreen-preview.rasi -show filebrowser -filebrowser-command 'awww img ' -filebrowser-directory ~/pictures/wallpaper -filebrowser-sorting-method mtime -selected-row 1 >/dev/null"

-- environment variables

hl.env("XCURSOR_SIZE", 24)
hl.env("HYPRCURSOR_SIZE", 24)
hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")

hl.config({
    general = {
        gaps_in = 0,
        gaps_out = 0,
        border_size = 2,
        resize_on_border = false,
        -- Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
        allow_tearing = false,
        layout = "dwindle",
        col = {
            active_border = active_border_gradient,
            inactive_border = inactive_border_gradient,
        },
    },
})

hl.config({
    decoration = {
        rounding = 0,
        active_opacity = 1.0,
        inactive_opacity = 1.0,
        shadow = {
            enabled = true,
            range = 4,
            render_power = 3,
            color = "rgba(1a1a1aee)",
        },
        blur = {
            enabled = true,
            size = 3,
            passes = 1,
            vibrancy = 0.1696,
        },
    },
})

hl.config({
    animations = {
        enabled = false,
    },
})

hl.curve("myBezier", {
    type = "bezier",
    points = { { 0.05, 0.9 }, { 0.1, 1.05 } },
})

hl.animation({ leaf = "windows", enabled = true, speed = 7, bezier = "myBezier" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 7, style = "popin 80%", bezier = "default" })
hl.animation({ leaf = "border", enabled = true, speed = 10, bezier = "default"  })
hl.animation({ leaf = "borderangle", enabled = true, speed = 8, bezier = "default"  })
hl.animation({ leaf = "fade", enabled = true, speed = 7, bezier = "default"  })
hl.animation({ leaf = "workspaces", enabled = true, speed = 6, bezier = "default"  })

hl.config({
    dwindle = {
        preserve_split = true,
        default_split_ratio = 1.5,
        force_split = 2,
    },
})

hl.config({
    master = {
        new_status = "inherit",
        orientation = "center",
    },
})

hl.config({
    ecosystem = {
        no_update_news = true,
        no_donation_nag = true,
    },
})

hl.config({
    misc = {
        force_default_wallpaper = -1,
        disable_hyprland_logo = true,
    },
})

hl.config({
    input = {
        kb_layout = "us",
        kb_options = "ctrl:nocaps",
        follow_mouse = 1,
        sensitivity = 0,
        numlock_by_default = true,
        touchpad = {
            natural_scroll = false,
        },
    },
})

hl.config({
    cursor = {
        hide_on_key_press = true,
    },
})

hl.device({
    name = "epic-mouse-v1",
    sensitivity = -0.5,
})

-- keybindings

local mainMod = "SUPER"

-- applications

hl.bind(mainMod .. " + " .. "RETURN", hl.dsp.exec_cmd("kitty"))
hl.bind(mainMod .. " + " .. "C", hl.dsp.exec_cmd("google-chrome-stable"))
hl.bind(mainMod .. " + " .. "Z", hl.dsp.exec_cmd("zen-browser"))
hl.bind(mainMod .. " + " .. "V", hl.dsp.exec_cmd("vivaldi"))
hl.bind(mainMod .. " + " .. "E", hl.dsp.exec_cmd("emacsclient -c"))
hl.bind(mainMod .. " + " .. "R", hl.dsp.exec_cmd("rofi -show combi -modes combi -combi-modes window,drun,run -show-icons -matching fuzzy -theme ~/.config/rofi/tokyonight.rasi"))
hl.bind(mainMod .. " + " .. "W", hl.dsp.exec_cmd("rofi -no-config -theme fullscreen-preview.rasi -show filebrowser -filebrowser-command 'awww img ' -filebrowser-directory ~/pictures/wallpaper -filebrowser-sorting-method mtime -selected-row 1 >/dev/null"))
hl.bind(mainMod .. " + " .. "S", hl.dsp.exec_cmd("bash -c 'grim -g \"$(slurp)\" - | wl-copy'"))

-- window manager
hl.bind(mainMod .. " + " .. "Q", hl.dsp.window.close())
hl.bind(mainMod .. " + " .. "M", hl.dsp.exit())
hl.bind(mainMod .. " + " .. "V", hl.dsp.window.float())
hl.bind(mainMod .. " + " .. "P", hl.dsp.window.pseudo())

-- dwindle

hl.bind(mainMod .. " + " .. "J", hl.dsp.layout("togglesplit"))

-- dwindle

hl.bind(mainMod .. " + " .. "apostrophe", hl.dsp.exec_cmd("hyprctl keyword general:layout master"))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "apostrophe", hl.dsp.exec_cmd("hyprctl keyword general:layout dwindle"))

-- move focus with mainmod + arrow keys

hl.bind(mainMod .. " + " .. "left", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + " .. "right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + " .. "up", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + " .. "down", hl.dsp.focus({ direction = "down" }))

-- switch workspaces with mainmod + [0-9]

hl.bind(mainMod .. " + " .. 1, hl.dsp.focus({ workspace = 1 }))
hl.bind(mainMod .. " + " .. 2, hl.dsp.focus({ workspace = 2 }))
hl.bind(mainMod .. " + " .. 3, hl.dsp.focus({ workspace = 3 }))
hl.bind(mainMod .. " + " .. 4, hl.dsp.focus({ workspace = 4 }))
hl.bind(mainMod .. " + " .. 5, hl.dsp.focus({ workspace = 5 }))
hl.bind(mainMod .. " + " .. 6, hl.dsp.focus({ workspace = 6 }))
hl.bind(mainMod .. " + " .. 7, hl.dsp.focus({ workspace = 7 }))
hl.bind(mainMod .. " + " .. 8, hl.dsp.focus({ workspace = 8 }))
hl.bind(mainMod .. " + " .. 9, hl.dsp.focus({ workspace = 9 }))

-- move active window to a workspace with mainmod + shift + [0-9]

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 1, hl.dsp.window.move({ workspace = 1 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 2, hl.dsp.window.move({ workspace = 2 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 3, hl.dsp.window.move({ workspace = 3 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 4, hl.dsp.window.move({ workspace = 4 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 5, hl.dsp.window.move({ workspace = 5 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 6, hl.dsp.window.move({ workspace = 6 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 7, hl.dsp.window.move({ workspace = 7 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 8, hl.dsp.window.move({ workspace = 8 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 9, hl.dsp.window.move({ workspace = 9 }))

-- swap

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "s", hl.dsp.layout("swapsplit"))

-- resize

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "right", hl.dsp.window.resize({ x = 10, y = 0, relative = true }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "left", hl.dsp.window.resize({ x = -10, y = 0, relative = true }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "up", hl.dsp.window.resize({ x = 0, y = -10, relative = true }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "down", hl.dsp.window.resize({ x = 0, y = 10, relative = true }))

-- example special workspace (scratchpad)

hl.bind(mainMod .. " + " .. "X", hl.dsp.workspace.toggle_special("magic"))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "X", hl.dsp.window.move({ workspace = "special:magic" }))

-- scroll through existing workspaces with mainmod + scroll

hl.bind(mainMod .. " + " .. "mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + " .. "mouse_up", hl.dsp.focus({ workspace = "e-1" }))

-- move/resize windows with mainmod + lmb/rmb and dragging

hl.bind(mainMod .. " + " .. "mouse:272", hl.dsp.window.drag(), { mouse = true })
hl.bind(mainMod .. " + " .. "mouse:273", hl.dsp.window.resize(), { mouse = true })

-- laptop multimedia keys for volume and lcd brightness

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+ --limit 1.0"), { locked = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"), { locked = true })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), { locked = true })
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"), { locked = true })
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl s 10%+"), { locked = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl s 10%-"), { locked = true })

-- windows and workspaces

hl.window_rule({
    name  = "suppress_event_maxim",
    match = {
        class = ".*",
    },
    suppress_event = "maximize"
})

hl.window_rule({
    name  = "no_blur_on",
    match = {
        class = "^()$",
        title = "^()$",
    },
    no_blur = true
})

hl.window_rule({
    name  = "opacity_1_override_1",
    match = {
        class = "kitty",
    },
    opacity = "1.0 override 1.0 override 1.0 override",
})

hl.window_rule({
    name  = "workspace_2",
    match = {
        class = "google-chrome",
    },
    workspace = 2,
})

hl.window_rule({
    name  = "workspace_2",
    match = {
        class = "zen",
    },
    workspace = 2,
})

hl.window_rule({
    name  = "workspace_2",
    match = {
        class = "vivaldi-stable",
    },
    workspace = 2,
})

hl.window_rule({
    name  = "float_on",
    match = {
        class = "zen",
        title = "Picture-in-Picture",
    },
    float = true,
})

hl.window_rule({
    name  = "workspace_3",
    match = {
        class = "Emacs",
    },
    workspace = 3,
})

hl.window_rule({
    name  = "workspace_4",
    match = {
        class = "jetbrains-idea-ce",
    },
    workspace = 4,
})

hl.window_rule({
    name  = "workspace_5",
    match = {
        class = "steam",
    },
    workspace = 5,
})

hl.window_rule({
    name  = "workspace_9",
    match = {
        class = "Bitwarden",
    },
    workspace = 9,
})

-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("waybar")
    hl.exec_cmd("awww-daemon")
    hl.exec_cmd("dunst")
end)
