-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- color definitions

local active_border_gradient = "rgba(64727Dff)"
local inactive_border_gradient = "rgba(191919ff)"
