#!/bin/sh

case "$1" in
"C-r")
        convert -rotate 90 "$2" "$2" ;;
"C-c")
        echo -n "$2" | xclip -selection clipboard ;;
"C-w")
        while read file; do 
         echo "setroot '-s' '${file}'" > ${HOME}/.config/setroot/.setroot-restore
         setroot --restore
        done;   
esac
